unique_ids:
  assets:
    standard-page.html: ROOR5FZIBYPHCEDSYTFVKSNXQXB73SZP
    theme.css: LLXEMWFXEZM6335P6WUMQEAPTAVRT4NY
  forms:
    Form1: THF7RJFMBDP73LRXRBIV2FPLOCUVWVSA
  modules: {}
  scripts: {}
  server_modules: {}
